const express = require('express');
const router = express.Router();
const verifyToken = require("../middleware/authMiddleware");
const authorizeRole = require("../middleware/roleMiddleware");
const verifyCookApproved = require("../middleware/cookApprovalMiddleware");
const { uploadDishImage } = require("../middleware/uploadMiddleware");
const { addMenu, getAllMenus, getCookMenus, getMenuById,updateMenu, deleteMenu } = require("../controllers/menuController");
router.post("/",verifyToken,authorizeRole("cook"),verifyCookApproved,uploadDishImage.single("image"),addMenu);
router.get("/",getAllMenus);
router.get("/my-menu",verifyToken,authorizeRole("cook"),verifyCookApproved,getCookMenus);
router.get("/:id",getMenuById);
router.put("/:id",verifyToken,authorizeRole("cook"),verifyCookApproved,uploadDishImage.single("image"),updateMenu);
router.delete("/:id",verifyToken,authorizeRole("cook"),verifyCookApproved,deleteMenu);
module.exports = router;
